<%@ Page Language="VB" AutoEventWireup="false" CodeFile="WFA010.aspx.vb" Inherits="WF_WFA010" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title></title>
    <link type="text/css" rel="stylesheet" href="../StyleSheet.Css" />
    <script type="text/javascript" language="javascript">
    <!--
        function redirectPage(Path) {
            window.parent.frames[3].frames[1].location = Path;
            //window.parent.frames[2].imgSplit_WorkFlow.src = "../images/mopen_r.png";  //20160725 Beatrice del
            window.parent.frames[2].imgSplit_WorkFlow.src = "../images/mopen.png";      //20160725 Beatrice modify
            //window.parent.frames[2].imgSplit_WorkFlow.alt = "Open WorkFlow menu";     //20160725 Beatrice del
            window.parent.frames[2].imgSplit_WorkFlow.alt = "Close WorkFlow menu"       //20160725 Beatrice modify
            //window.parent.frmSet.cols = "0,0,20,*"; //20160725 Beatrice del
            window.parent.frmSet.cols = "0,360,20,*"; //20160725 Beatrice modify
            //window.parent.frames[2].document.bgColor = '#c10c0c';
            window.parent.frames[2].document.bgColor = '#f1f1f1';   //20150320 wei modify

            if (Path.indexOf("ExitFlow") >= 0)
                WFStepCloseMenu();
            
            showSubmitting();
            window.setTimeout("checkStatus()", 500)
        }
        
        function checkStatus()
        {
            var msg;
			try
			{
				var obj = window.parent.frames[3].frames[1].document.getElementById('__ActionParam');
				msg = obj.value;
				hidePopupWindow();
			}
			catch(ex)
			{
				window.setTimeout("checkStatus()", 100);
			}
        }
        
         function WFStepCloseMenu()
        {
            window.parent.frames[1].location = "WFA010.aspx";
            window.parent.frames[2].imgSplit_WorkFlow.src = "";
            window.parent.frames[2].imgSplit_WorkFlow.alt = "";
            //window.parent.frmSet.cols = "0,0,20,*";  //20160725 Beatrice del
            window.parent.frmSet.cols = "360,0,20,*";  //20160725 Beatrice modify
            window.parent.frames[2].imgSplit_WorkFlow.style.display = "none";
            window.parent.frames[2].imgSplit.src = "../images/mclose.png";  //20160725 Beatrice add
            window.parent.frames[2].imgSplit.alt = "Close menu";            //20160725 Beatrice add
        }
    -->
    </script>
</head>
<body style="margin-right:5; margin-left:5; margin-top:10; margin-bottom:10; background: url(../images/menu.gif)">
    <form id="frmContent" runat="server" style="margin-left:0px">    
    <div>
        <table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
            <tr>
                <td width="100%" runat="Server" id="tdHeadLine" style="font-size:16px; font-weight:normal; color:blue; font-family:Calibri;">&nbsp;</td>
            </tr>
        </table>
        <asp:PlaceHolder ID="phTree" runat="server">
        <asp:TreeView ID="FvFun" runat="server" ShowLines="true" AutoGenerateDataBindings="false" BackColor="transparent" Font-Size="16px" ForeColor="black">
        <NodeStyle Font-Size="16px" ForeColor="black" />
        <HoverNodeStyle Font-Underline="true" />
        <ParentNodeStyle ImageUrl="~/images/folder2.gif" />
        <RootNodeStyle ImageUrl="~/images/folder2.gif" />
        <LeafNodeStyle ImageUrl="~/images/html2.gif" />
        </asp:TreeView>
    </asp:PlaceHolder>
        &nbsp; &nbsp;&nbsp;
    </div>    
    </form>
</body>
</html>
